# Generated by Django 3.1.2 on 2020-11-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionmodel',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
    ]
