# Generated by Django 3.1.2 on 2020-11-22 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='菜单')),
                ('url', models.CharField(max_length=255, verbose_name='菜单url')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menu', verbose_name='父级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=255, verbose_name='菜单权限')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menu', verbose_name='菜单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
